---
# model_and_diffusion_defaults
image_size: 32
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
attention_resolutions: "16,8"
dropout: 0.1
learn_sigma: False
sigma_small: False
class_cond: False
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
use_checkpoint: False
use_scale_shift_norm: False

# sample defaults
clip_denoised: True
num_samples: 10000
batch_size: 1250
use_ddim: False
model_path:  # path to the model 
progress: True
timestep_respacing:

# wdp defaults
wdp_sample: False
wdp_process_demo: False
wdp_gamma1: 
wdp_gamma2: 
wdp_key: 
wdp_trigger_type: 
wdp_trigger_path: 
use_fp16: False
weight_perturb_std: 0