---
data_dir: "datasets/cifar_train"
schedule_sampler: "uniform"
lr: 1.0e-4
weight_decay: 0.0
lr_anneal_steps: 0
batch_size: 32 #32*4=128
microbatch: -1  
ema_rate: "0.999" 
log_interval: 10
save_interval: 1000
use_fp16: False
fp16_scale_growth: 1.0e-3

# model_and_diffusion_defaults
image_size: 32
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
attention_resolutions: "16,8"
dropout: 0.1
learn_sigma: False
sigma_small: False
class_cond: False
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
use_checkpoint: False
resume_checkpoint: 
use_scale_shift_norm: False

# wdp defaults
wm_embed: True
wm_data_dir: "datasets/single_wm"
wm_batch_size: 32
wdp_gamma1: 0.8
wdp_gamma2: 0.1
wdp_key: 1998
wdp_trigger_type: 0
wdp_trigger_path: "datasets/imgs/trigger_sel.jpg"